name: Main
author: Rae
version: 1.0
main: me.Rae.Main.Main
description: Main for me.

commands:
  giveitem:
    usage: /<command>
    description: Main Command
  tutorial:
    usage: /<command>
    description: Main Command